AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Send Email - Lambda Function
Parameters:
  SenderEmail:
    Description: Sender email
    Type: String
  RecipientEmail:
    Description: Recipient email
    Type: String
  SenderPassword:
    Description: Sender password
    Type: String

Resources:
  
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendEmailContactFn
      Description: Send e-mail about our contact space
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 7
      Environment:
        Variables:
          SenderEmail: !Ref SenderEmail
          RecipientEmail: !Ref RecipientEmail
          SenderPassword: !Ref SenderPassword

  SendEmailFunctionUrl:
    Type: AWS::Lambda::Url
    Properties: 
      AuthType: NONE
      Cors: 
        AllowCredentials: false
        AllowHeaders: 
          - "Content-Type"
        AllowMethods: 
          - POST
          - OPTIONS
        AllowOrigins: 
          - "https://dak1pni58hzx7.cloudfront.net"
        MaxAge: 3600
      TargetFunctionArn: !GetAtt SendEmailFunction.Arn

  ApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SendEmailFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref AWS::AccountId