AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Send Email - Lambda Function
Parameters:
  SenderEmail:
    Description: Sender email
    Type: String
  RecipientEmail:
    Description: Recipient email
    Type: String
  SenderPassword:
    Description: Sender password
    Type: String

Globals:
  Function:
    Timeout: 7

Resources:
  
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        SenderEmail:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          SenderEmail: !Ref SenderEmail
          RecipientEmail: !Ref RecipientEmail
          SenderPassword: !Ref SenderPassword
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile