AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Send Email - Lambda Function
Parameters:
  SenderEmail:
    Description: Sender email
    Type: String
  RecipientEmail:
    Description: Recipient email
    Type: String
  SenderPassword:
    Description: Sender password
    Type: String

Resources:
  
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sender email Lambda Fn
      FunctionName: EscolaDeSoftware-SenderEmailContactFn
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs16.x
      Timeout: 7
      Events:
        SenderEmail:
          Type: Api
          Properties:
            Path: /email
            Method: POST
      Environment:
        Variables:
          SenderEmail: !Ref SenderEmail
          RecipientEmail: !Ref RecipientEmail
          SenderPassword: !Ref SenderPassword